
package:
  name: gridtools
  version: 0.4.0.dev

source:
  git_url: https://github.com/CAB-LAB/gridtools.git
#  git_rev: v0.4.0rc0+1

build:
  number: 0

requirements:
  build:
    - python 3.6*
    - numpy >=1.13
    - numba >=0.34

  run:
    - python
    - numpy >=1.13
    - numba >=0.34

test:
  imports:
    - gridtools
    - gridtools.resampling
    - gridtools.gapfilling

about:
  home: https://github.com/CAB-LAB/gridtools
  license: MIT
  license_file: LICENSE

