language: python
python:
  - "3.6"
  - "3.5"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - sed -i "s/python >=3.5/python =="$(echo $TRAVIS_PYTHON_VERSION)"/g" environment.yml
  - conda env create --file environment.yml;
  - source activate gridtools
  - python setup.py install

script:
  - export NUMBA_DISABLE_JIT=1
  - py.test -v --cov=gridtools test/

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
