name: gridtools
channels:
    - conda-forge
    - numba
    - anaconda
dependencies:
    - python ==3.6
    - numpy=1.13.1=py36_0
    - numba=0.34.0=np113py36_5
    #
    # for testing only
    #
    - pytest
    - pytest-cov