name: gridtools
channels:
    - conda-forge
    - numba
    - anaconda
dependencies:
    - python >=3.5
    - numpy>=1.13,<2.0
    - numba>0.35,<1.0
    #
    # for testing only
    #
    - pytest
    - pytest-cov