name: gridtools
channels:
    - conda-forge
    - numba
    - anaconda
dependencies:
    - python ==3.5
    - numpy=1.13.1=py35_0
    - numba=0.35.0=np113py35_0
    #
    # for testing only
    #
    - pytest
    - pytest-cov